- id: elixir-mix-format
  name: mix format
  language: system
  entry: mix format
  files: \.exs?$
- id: elixir-mix-credo
  name: mix credo
  language: system
  entry: mix credo
  pass_filenames: false
- id: elixir-mix-deps-check-unused
  name: mix deps.unlock
  language: system
  entry: mix deps.unlock --check-unused
  stages: [push]
  pass_filenames: false
- id: elixir-mix-dialyzer
  name: mix dialyzer
  language: system
  entry: mix dialyzer
  stages: [push]
  pass_filenames: false
- id: elixir-mix-test
  name: mix test
  language: system
  entry: mix test
  stages: [push]
  pass_filenames: false
